### ISSUE TITLE
Doesnt emit any events

### ISSUE THREAD

**Issue by dhivehi** [p80-ch/mysql-binlog-emitter#2]
I checked this. But no event is triggering even after the script has been started successfully. And no errors in output.

**Comment by frank-dspeed** [comment]
@dhivehi  this is a new project and it is awsome !!!! I hope he makes progress in this as this is really next level shit for mysql simply help @stz443 to complet this and don't blame around here.

**Comment by stz443** [comment]
We use this project in production to sync data with a kiosk, since spring '18. I can assure you, that its stable and that it works as advertised. 
@dhivehi make sure you configured your db for master/slave replication. And subscribe to "Event.ANY" for testing, this way you will receive all events, including errors. If you keep having issues, post the relevant parts of your my.conf or your implementation.
